/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        lightcrew: {
          primary: "#007AFF",
          "primary-content": "#FFFFFF",
          secondary: "#C2DFFF",
          "secondary-content": "#041326",
          accent: "#041326",
          "accent-content": "#FFFFFF",
          neutral: "#90A1B4",
          "neutral-content": "#FFFFFF",
          "base-50": "#FFFFFF",
          "base-100": "#F9FAFB",
          "base-200": "#F3F4F6",
          "base-300": "#E5E7EB",
          info: "#53B0E9",
          "info-content": "#FFFFFF",
          success: "#28C76F",
          "success-content": "#FFFFFF",
          warning: "#FFB547",
          "warning-content": "#041326",
          error: "#FF5A5F",
          "error-content": "#FFFFFF",
        },
        darkcrew: {
          primary: "#4AAFFF",
          "primary-content": "#0B1120",
          secondary: "#2B4C68",
          "secondary-content": "#F5F7FA",
          accent: "#F5F7FA",
          "accent-content": "#0B1120",
          neutral: "#7A8CA2",
          "neutral-content": "#F5F7FA",
          "base-50": "#0B1120",
          "base-100": "#121828",
          "base-200": "#1C2537",
          "base-300": "#2E3A4A",
          info: "#4DA8F7",
          "info-content": "#0B1120",
          success: "#3FBD76",
          "success-content": "#0B1120",
          warning: "#FFA63E",
          "warning-content": "#0B1120",
          error: "#FF6D7A",
          "error-content": "#0B1120",
        },
      },
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
  },
};
